# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
