# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_bookdata_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='CSVURL',
        ),
    ]
