# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_bookdata_csvurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='CSVURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
